### DISCUSSION TITLE
Branch Prediction

### DISCUSSION THREAD

**Discussion by arupc** [riscv-software-src/riscv-perf-model#125] [Ideas]
Per previous discussion, we would like to develop an API that can support various branch prediction implementations, including possibly any existing open-source implementations. 

As an example, the API should be such that it can support:
* a simple oracle predictor
* BOOM's branch predictor, as described here: https://docs.boom-core.org/en/latest/sections/branch-prediction/index.html

Output of the branch predictor is a [Fetch Packet](https://docs.boom-core.org/en/latest/sections/terminology.html#term-fetch-packet). Each Fetch Packet represents a sequence of instructions and is characterized by at least :
* Fetch PC, the pc of the first valid instruction in the Fetch Packet
* Number of instructions in the Fetch Packet

Thus a simple API would like:

```
class FetchPacket {
    uint64_t FetchPC;
    uint32_t num_insts;
    <implementation-specific-attributes>; // may be added using a template parameter?
};
```

**Comment by danbone** [comment]
Sorry we had an internet outage during the SIG meeting, so I missed the last 10 minutes.

Initially I didn't want to change the current Fetch implementation too much. The idea was to have separate units instanced underneath it:
- Branch Target Buffer
- Return Address Stack
- Direction Predictor (gshare/TAGE/Perceptron etc)
- Indirect Target Predictor (ITAGE)

Each of these would have their own parameter set, and the user could configure the topology of fetch to swap different algorithms in and out.  An example configuration file:

```
top.cpu.core0.fetch.params:
  predictor: "TAGE"
  tage.params:
    history_tables: 7
    min_hist_size: 5
    max_hist_size: 130
    table_tag_widths: [0, 9, 9, 10, 10, 11, 11, 12]
    log2_table_sizes: [13, 9, 9, 9, 9, 9, 9, 9]
    bimodel_counter_bits: 4
    tage_table_counter_bits: 3
    tage_table_u_bits: 2
    path_hist_bits: 16
  btb.params:
    num_entries: 4096
    associativity: 8
    block_size: 64
  ras.params:
    num_entries: 16
```

(I'm not sure how feasible this is yet)

As for the API, maybe it would be better if I placed the sub-components under a separate BranchPred component rather than fetch so we have a single point of interaction under multiple fetch implementations. 

Though I'm not sure how practical it would be as the complexity grows. For example if we had a fetch with a small BTB providing fetch PCs in 1 cycle, then a larger BTB which overrides the earlier prediction 2 cycles later (similar to BOOM IIRC). Then it would be heavily coupled with the fetch logic, and the BranchPred API might not be flexible enough for both implementations.

Similarly if the predictor sub-components are hidden under BranchPred then it could make more complex topologies more difficult to implement. i.e. a BTB with a separate prefetch port.


What are you thoughts?


FWIW I started a simple predictor earlier today using an API like:
- Predict an instruction using an address, outputs the direction and some meta data in a implementation structure i.e. index of counter
- Speculative update with a unique ID and the meta data captured from the prediction (prediction might be from a different component i.e. RAS), this would update the history registers and track the meta data using the unique ID provided.
- Flush - restores any state to the what it was previously to the speculative update with the unique ID given
- Update - Clean up, and update state for the unique ID
